# Evaluation query for GTFS data set: find all pairs of stops that are within
# 25 meters of each other
PREFIX gtfs: <http://vocab.gtfs.org/terms#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX geof: <http://www.opengis.net/def/function/geosparql/>

SELECT (AVG(?count) AS ?avg_count) WHERE {
  {
    SELECT (COUNT(*) AS ?count) WHERE {
      ?stop1 a gtfs:Stop ;
            rdfs:member gtfs:feed_%FEED% ;
            geo:hasCentroid/geo:asWKT ?centroid1 .
      ?stop2 a gtfs:Stop ;
             rdfs:member gtfs:feed_%FEED% ;
             geo:hasCentroid/geo:asWKT ?centroid2 .
      FILTER(geof:distance(?centroid1, ?centroid2) <= 0.1)
    }
    GROUP BY ?stop1
  }
}
